import { useState } from 'react';

interface Message {
  id: string;
  question: string;
  answer: string;
  timestamp: Date;
  isLoading?: boolean;
}

// Demo data
const demoMessages: Message[] = [
  {
    id: '1',
    question: 'What are the main challenges in the current sprint?',
    answer:
      "Based on the team's performance data, the main challenges are:\n1. Code review bottlenecks\n2. Technical debt accumulation\n3. Integration issues with the new API",
    timestamp: new Date('2024-03-15T10:00:00'),
  },
  {
    id: '2',
    question: 'How can we improve team velocity?',
    answer:
      'To improve team velocity, consider:\n1. Implementing pair programming sessions\n2. Reducing context switching\n3. Optimizing the CI/CD pipeline',
    timestamp: new Date('2024-03-15T10:30:00'),
  },
];

export const Prompt = () => {
  const [messages, setMessages] = useState<Message[]>(demoMessages);
  const [inputValue, setInputValue] = useState('');
  const [editingMessageId, setEditingMessageId] = useState<string | null>(null);
  const MAX_INPUT_LENGTH = 500;

  const handleSend = () => {
    if (!inputValue.trim()) return;

    if (editingMessageId) {
      // Update existing message
      setMessages(
        messages.map((msg) =>
          msg.id === editingMessageId ? { ...msg, question: inputValue } : msg
        )
      );
      setEditingMessageId(null);
    } else {
      // Add new message
      const newMessage: Message = {
        id: Date.now().toString(),
        question: inputValue,
        answer: '',
        timestamp: new Date(),
        isLoading: true,
      };
      setMessages([...messages, newMessage]);

      // Simulate API call
      setTimeout(() => {
        setMessages((prevMessages) =>
          prevMessages.map((msg) =>
            msg.id === newMessage.id
              ? {
                  ...msg,
                  answer:
                    'This is a demo answer. In a real implementation, this would be generated by an AI model.',
                  isLoading: false,
                }
              : msg
          )
        );
      }, 1500);
    }
    setInputValue('');
  };

  const handleRegenerate = (messageId: string) => {
    setMessages(
      messages.map((msg) =>
        msg.id === messageId ? { ...msg, isLoading: true } : msg
      )
    );

    // Simulate API call
    setTimeout(() => {
      setMessages((prevMessages) =>
        prevMessages.map((msg) =>
          msg.id === messageId
            ? {
                ...msg,
                answer: 'This is a regenerated demo answer.',
                isLoading: false,
              }
            : msg
        )
      );
    }, 1500);
  };

  const handleDelete = (messageId: string) => {
    setMessages(messages.filter((msg) => msg.id !== messageId));
  };

  const handleEdit = (messageId: string) => {
    const message = messages.find((msg) => msg.id === messageId);
    if (message) {
      setInputValue(message.question);
      setEditingMessageId(messageId);
    }
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const handleClear = () => {
    setInputValue('');
    setEditingMessageId(null);
  };

  return (
    <div className="flex flex-col w-full max-w-3xl mx-auto space-y-4">
      {/* Messages */}
      <div className="space-y-4">
        {messages.map((message) => (
          <div key={message.id} className="bg-[#2a2f4a] rounded-lg p-4">
            <div className="flex justify-between items-start mb-2">
              <div className="text-gray-300">{message.question}</div>
              <div className="flex gap-2">
                <button
                  onClick={() => handleRegenerate(message.id)}
                  className="text-gray-400 hover:text-[#f8d94e] transition-colors"
                  title="Regenerate answer"
                >
                  {message.isLoading ? (
                    <span className="animate-spin">⟳</span>
                  ) : (
                    '↻'
                  )}
                </button>
                <button
                  onClick={() => handleEdit(message.id)}
                  className="text-gray-400 hover:text-[#f8d94e] transition-colors"
                  title="Edit question"
                >
                  ✎
                </button>
                <button
                  onClick={() => handleCopy(message.answer)}
                  className="text-gray-400 hover:text-[#f8d94e] transition-colors"
                  title="Copy answer"
                >
                  ⎘
                </button>
                <button
                  onClick={() => handleDelete(message.id)}
                  className="text-gray-400 hover:text-red-500 transition-colors"
                  title="Delete message"
                >
                  ×
                </button>
              </div>
            </div>
            <div className="text-white whitespace-pre-line">
              {message.isLoading ? (
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-[#f8d94e] rounded-full animate-bounce" />
                  <div className="w-2 h-2 bg-[#f8d94e] rounded-full animate-bounce delay-100" />
                  <div className="w-2 h-2 bg-[#f8d94e] rounded-full animate-bounce delay-200" />
                </div>
              ) : (
                message.answer
              )}
            </div>
            <div className="text-xs text-gray-500 mt-2">
              {message.timestamp.toLocaleTimeString()}
            </div>
          </div>
        ))}
      </div>

      {/* Input */}
      <div className="flex flex-col gap-2">
        <div className="flex gap-2">
          <div className="relative flex-1">
            <input
              type="text"
              value={inputValue}
              onChange={(e) =>
                setInputValue(e.target.value.slice(0, MAX_INPUT_LENGTH))
              }
              onKeyPress={(e) => e.key === 'Enter' && handleSend()}
              placeholder={
                editingMessageId ? 'Edit your question...' : 'Ask a question...'
              }
              className="w-full px-4 py-2 bg-[#2a2f4a] text-white rounded-lg focus:outline-none focus:ring-2 focus:ring-[#f8d94e]"
            />
            {inputValue && (
              <button
                onClick={handleClear}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white"
              >
                ×
              </button>
            )}
          </div>
          <button
            onClick={handleSend}
            disabled={!inputValue.trim()}
            className="px-6 py-2 bg-[#f8d94e] text-black font-semibold rounded-lg hover:bg-[#e6c73d] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {editingMessageId ? 'Update' : 'Send'}
          </button>
        </div>
        <div className="flex justify-between text-xs text-gray-500">
          <span>
            {inputValue.length}/{MAX_INPUT_LENGTH} characters
          </span>
          {editingMessageId && (
            <button
              onClick={() => {
                setEditingMessageId(null);
                setInputValue('');
              }}
              className="text-[#f8d94e] hover:text-[#e6c73d]"
            >
              Cancel editing
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
